export const siteConfig = {
  name: "UK Calculator Hub",
  shortName: "UK Calculator Hub",
  description:
    "Simple UK calculators for salary, take-home pay, rent, mortgage, pension, hourly wage and cost of living with clear visual breakdowns.",
  url: "https://ukcalchub.co.uk",
};

export const siteRoutes = [
  "/",
  "/about",
  "/editorial-policy",
  "/contact",
  "/privacy-policy",
  "/disclaimer",
  "/salary-calculator-uk",
  "/take-home-pay-calculator-uk",
  "/salary-rent-affordability-calculator-uk",
  "/pension-contribution-calculator-uk",
  "/rent-affordability-calculator-uk",
  "/cost-of-living-calculator-uk",
  "/hourly-wage-calculator-uk",
  "/mortgage-affordability-calculator-uk",
  "/salary-after-tax-25000-uk",
  "/salary-after-tax-28000-uk",
  "/salary-after-tax-30000-uk",
  "/salary-after-tax-32000-uk",
  "/salary-after-tax-35000-uk",
  "/salary-after-tax-38000-uk",
  "/salary-after-tax-40000-uk",
  "/salary-after-tax-42000-uk",
  "/salary-after-tax-45000-uk",
  "/salary-after-tax-50000-uk",
  "/salary-after-tax-55000-uk",
  "/salary-after-tax-60000-uk",
  "/salary-after-tax-70000-uk",
  "/salary-after-tax-80000-uk",
  "/salary-after-tax-100000-uk",
  "/why-is-my-payslip-different-from-salary-calculator-uk",
  "/what-is-1257l-tax-code-uk",
  "/what-is-salary-sacrifice-uk",
  "/uk-personal-allowance-2026-27",
  "/how-does-pension-auto-enrolment-work-uk",
  "/what-is-national-insurance-uk",
] as const;
