export const taxCodeOptions = [
  { label: "1257L - Standard allowance", value: "1257L" },
  { label: "0T - No personal allowance", value: "0T" },
  { label: "BR - Basic rate", value: "BR" },
  { label: "D0 - Higher rate", value: "D0" },
  { label: "D1 - Additional rate", value: "D1" },
  { label: "NT - No tax", value: "NT" },
  { label: "K497 - Extra taxable pay", value: "K497" },
  { label: "K1257 - Higher taxable adjustment", value: "K1257" },
  { label: "S1257L - Scotland standard", value: "S1257L" },
  { label: "S0T - Scotland no allowance", value: "S0T" },
  { label: "SBR - Scotland basic rate", value: "SBR" },
  { label: "SD0 - Scotland intermediate rate", value: "SD0" },
  { label: "SD1 - Scotland higher rate", value: "SD1" },
  { label: "SD2 - Scotland advanced rate", value: "SD2" },
  { label: "SD3 - Scotland top rate", value: "SD3" },
  { label: "C1257L - Wales standard", value: "C1257L" },
  { label: "C0T - Wales no allowance", value: "C0T" },
  { label: "CBR - Wales basic rate", value: "CBR" },
  { label: "CD0 - Wales higher rate", value: "CD0" },
  { label: "CD1 - Wales additional rate", value: "CD1" },
] as const;
